pipeline {
    agent any
     parameters {
        string(name: 'REPO_URL', defaultValue: '', description: 'The Git repository URL to clone')
        string(name: 'BRANCH', defaultValue: '', description: 'The branch to build (e.g., main or master)')
        string(name: 'SUB_DIR', defaultValue: '', description: 'Subdirectory where the frontend code lives (leave blank if in root)')
        string(name: 'USERNAME', defaultValue: '', description: 'Name of the user triggering the build')
        string(name: 'USER_ID', defaultValue: '', description: 'ID of the user')
        string(name: 'EMAIL', defaultValue: '', description: 'Email address for build notifications')
    }
    stages {
      stage('Clone') {
            steps {
                script {
                    env.FOLDER_NAME = env.REPO_URL.tokenize('/').last().minus('.git').toLowerCase()
                    
                    if (env.SUB_DIR?.trim()) {
                        env.BUILD_DIR = "${env.FOLDER_NAME}/${env.SUB_DIR}"
                    } else {
                        env.BUILD_DIR = env.FOLDER_NAME
                    }
                    
                    // Wipe out the old folder to prevent Git permission conflicts
                    sh "rm -rf ${env.FOLDER_NAME}"
                    
                    dir(env.FOLDER_NAME) {
                        git url: "${env.REPO_URL}", branch: "${env.BRANCH}"
                    }
                }
            }
        }
        
        stage('Install Modules & Build') {
            steps {
                dir(env.BUILD_DIR) {
                    nodejs(nodeJSInstallationName: '24.9.0') {
                        sh '''
                            npm install -g pnpm
                            pnpm install 
                            pnpm run build
                        '''
                    }
                }
            }
        }

        stage('Deploy to Bare-Metal NGINX') {
            steps {
                sh '''
                    # Copy to the Master Node's physical web directory
                    mkdir -p /srv/http/$FOLDER_NAME
                    cp -r $WORKSPACE/$BUILD_DIR/dist/* /srv/http/$FOLDER_NAME/
                    
                    # Ensure NGINX has permission to read the files
                    chmod -R 755 /srv/http/$FOLDER_NAME
                '''
            }
        }
    }
    post {
        success {
            sh """
                curl -X POST -H "Content-Type: application/json" \
                -d '{"build": "${env.BUILD_NUMBER}", "status": "${currentBuild.currentResult}", "user": "${env.USERNAME}", "user_id": "${env.USER_ID}", "email": "${env.EMAIL}", "hosted_site_url": "http://${env.FOLDER_NAME}.3.111.41.38.nip.io", "repo_url":"${env.REPO_URL}", "branch": "${env.BRANCH}", "subDirectory":"${env.SUB_DIR}"}' \
                http://hosty-backend:5001/api/webhook/jenkinsWebhook/
            """
        }
        
        failure {
            sh """
                curl -X POST -H "Content-Type: application/json" \
                -d '{"build": "${env.BUILD_NUMBER}", "status": "${currentBuild.currentResult}", "user": "${env.USERNAME}", "user_id": "${env.USER_ID}", "email": "${env.EMAIL}", "hosted_site_url": "http://${env.FOLDER_NAME}.3.111.41.38.nip.io", "repo_url":"${env.REPO_URL}", "branch": "${env.BRANCH}", "subDirectory":"${env.SUB_DIR}"}' \
                http://hosty-backend:5001/api/webhook/jenkinsWebhook/
            """
        }
    }
}