apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hosty-postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.storage.postgresSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosty-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hosty-postgres
  template:
    metadata:
      labels:
        app: hosty-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:18.3
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: hosty-secrets
        volumeMounts:  
        - name: pg-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: hosty-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hosty-postgres-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: hosty-postgres
  ports:
    - port: 5432