apiVersion: v1
kind: Secret
metadata:
  name: hosty-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  GITHUB_CLIENT_ID: {{ .Values.secrets.GITHUB_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.GITHUB_CLIENT_SECRET }}
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD }}
  JENKINS_USERNAME: {{ .Values.secrets.JENKINS_USERNAME }}
  JENKINS_API_TOKEN: {{ .Values.secrets.JENKINS_API_TOKEN }}
  JENKINS_CRUMB: {{ .Values.secrets.JENKINS_CRUMB }}
  JENKINS_URL: {{ .Values.secrets.JENKINS_URL }}
  FRONTEND_URL: {{ .Values.secrets.FRONTEND_URL }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL }}