apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hosty-jenkins-vpa
  namespace: hosty-ns
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hosty-jenkins-deployment

  updatePolicy:
    updateMode: "Auto" 