server {
    listen 80;

    # Catch all requests aimed at your EC2's nip.io domain
    server_name ~^(?<subdomain>[a-zA-Z0-9-]+)\.3\.111\.41\.38\.nip\.io$;

    # Point NGINX to the specific user's folder
    location / {
        root /usr/share/nginx/html/$subdomain;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}

# Add a default server block to catch everything else (so it doesn't default to the welcome page)
server {
    listen 80 default_server;
    server_name _;
    return 404; # Or redirect to your React frontend: return 301 http://3.111.41.38:8080;