apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flow-auto-ingress
  namespace: flow-auto-ns
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: flow-auto-backend-svc
            port:
              number: 5001

      - path: /
        pathType: Prefix
        backend:
          service:
            name: flow-auto-frontend-svc
            port:
              number: 80