kind: Deployment
apiVersion: apps/v1

metadata:
  name: hosty-backend-deployment
  namespace: hosty-ns
  labels:
    app: hosty-backend-dep

spec:
  replicas: 2
  selector:
    matchLabels:
      app: hosty-backend-pod-classify

  template:
    metadata:
      name: hosty-backend-pod
      namespace: hosty-ns
      labels:
        app: hosty-backend-pod-classify

    spec:
      containers:
      - name: hosty-backend-container
        image:
          context: ../../../server
        ports:
        - containerPort: 5001
        
        envFrom:
          - secretRef:
              name: hosty-backend-secret

        resources:
          requests:
            cpu: "250m"      
            memory: "256Mi"
          limits:
            cpu: "500m"      
            memory: "512Mi"