kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2

metadata:
  name: hosty-backend-hpa
  namespace: hosty-ns

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hosty-backend-deployment

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70