kind: Deployment
apiVersion: apps/v1

metadata:
  name: hosty-frontend-deployment
  namespace: hosty-ns
  labels:
    app: hosty-frontend-dep

spec:
  replicas: 2
  selector:
    matchLabels:
      app: hosty-frontend-pod-classify

  template:
    metadata:
      name: hosty-frontend-pod
      namespace: hosty-ns
      labels:
        app: hosty-frontend-pod-classify

    spec:
      containers:
      - name: hosty-frontend-container
        image:
          context: ../../../frontend
        ports:
        - containerPort: 80
