apiVersion: v1
kind: Service
metadata:
  name: flow-auto-frontend-svc
  namespace: flow-auto-ns
spec:
  selector:
    app: flow-auto-frontend-pod-classify
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80    

