apiVersion: v1
kind: Service
metadata:
  name: hosty-frontend-svc
  namespace: hosty-ns
spec:
  selector:
    app: hosty-frontend-pod-classify
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80    

