# values.yaml
namespace: hosty-ns
domain: "3.6.87.214.nip.io"

images:
  backend: "aashu1412/hosty-backend:latest" 
  frontend: "aashu1412/hosty-frontend:latest" 

secrets:
  GITHUB_CLIENT_ID: <YOUR_BASE64_GITHUB_CLIENT_ID>
  GITHUB_CLIENT_SECRET: <YOUR_BASE64_GITHUB_CLIENT_SECRET>
  JENKINS_USERNAME: <YOUR_BASE64_JENKINS_USERNAME>
  JENKINS_API_TOKEN: <YOUR_BASE64_JENKINS_API_TOKEN>
  JENKINS_CRUMB: <YOUR_BASE64_JENKINS_CRUMB>
  JWT_SECRET_KEY: <YOUR_BASE64_JWT_SECRET_KEY>
  JENKINS_URL: <YOUR_BASE64_JENKINS_URL>
  FRONTEND_URL: <YOUR_BASE64_FRONTEND_URL>
  DATABASE_URL: <YOUR_BASE64_DATABASE_URL>
  POSTGRES_USER: <YOUR_BASE64_POSTGRES_USER>
  POSTGRES_PASSWORD: <YOUR_BASE64_POSTGRES_PASSWORD>

storage:
  postgresSize: 500Mi