apiVersion: v1
kind: Service
metadata:
  name: hosty-postgres-svc
  namespace: hosty-ns
spec:
  selector:
    app: hosty-postgres-pod-classify
  ports:
    - protocol: TCP
      port: 5432          
      targetPort: 5432    
  type: ClusterIP      